In [236]:
## Standard Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
## Importing the OS and JSON Modules
import os,json

In [237]:
# Loading data
df_info = pd.read_csv('Data//superhero_info - superhero_info.csv')
df_powers = pd.read_csv('Data//superhero_powers - superhero_powers.csv')

In [238]:
df_info

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"
...,...,...,...,...,...,...,...,...
458,Yellowjacket|Marvel Comics,Male,Human,good,Blond,blue,Unknown,"{'Height': '183.0 cm', 'Weight': '83.0 kg'}"
459,Yellowjacket II|Marvel Comics,Female,Human,good,Strawberry Blond,blue,Unknown,"{'Height': '165.0 cm', 'Weight': '52.0 kg'}"
460,Yoda|George Lucas,Male,Yoda's species,good,White,brown,green,"{'Height': '66.0 cm', 'Weight': '17.0 kg'}"
461,Zatanna|DC Comics,Female,Human,good,Black,blue,Unknown,"{'Height': '170.0 cm', 'Weight': '57.0 kg'}"
462,Zoom|DC Comics,Male,Unknown,bad,Brown,red,Unknown,"{'Height': '185.0 cm', 'Weight': '81.0 kg'}"

In [239]:
df_powers

          hero_names                                             Powers
0            3-D Man         Agility,Super Strength,Stamina,Super Speed
1             A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2         Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3           Abin Sur                                 Lantern Power Ring
4        Abomination  Accelerated Healing,Intelligence,Super Strengt...
..               ...                                                ...
662  Yellowjacket II                 Flight,Energy Blasts,Size Changing
663             Ymir  Cold Resistance,Durability,Longevity,Super Str...
664             Yoda  Agility,Stealth,Danger Sense,Marksmanship,Weap...
665          Zatanna  Cryokinesis,Telepathy,Magic,Fire Control,Proba...
666             Zoom  Super Speed,Intangibility,Time Travel,Time Man...

[667 rows x 2 columns]

In [240]:
df_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Hero|Publisher  463 non-null    object
 1   Gender          463 non-null    object
 2   Race            463 non-null    object
 3   Alignment       463 non-null    object
 4   Hair color      463 non-null    object
 5   Eye color       463 non-null    object
 6   Skin color      463 non-null    object
 7   Measurements    463 non-null    object
dtypes: object(8)
memory usage: 29.1+ KB

In [241]:
df_powers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hero_names  667 non-null    object
 1   Powers      667 non-null    object
dtypes: object(2)
memory usage: 10.5+ KB

In [242]:
## save the 2 new columns into the dataframe
df_info[['Hero','Publisher']] = df_info['Hero|Publisher'].str.split('|',expand=True)
df_info.head(3)

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics

In [243]:
## drop the original column
df_info = df_info.drop(columns=['Hero|Publisher'])
df_info.head(3)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics

In [244]:
# measurements column
df_info['Measurements'].head(5)

0    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
1     {'Height': '191.0 cm', 'Weight': '65.0 kg'}
2     {'Height': '185.0 cm', 'Weight': '90.0 kg'}
3    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
4    {'Height': '193.0 cm', 'Weight': '122.0 kg'}
Name: Measurements, dtype: object

In [245]:
# split Measuremnts column into 2 column Height and Weight
df_info[['Height(cm)', 'Weight(kg)']] = df_info['Measurements'].str.split(',', expand=True)
df_info.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher,Height(cm),Weight(kg)
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics,{'Height': '203.0 cm','Weight': '441.0 kg'}
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics,{'Height': '191.0 cm','Weight': '65.0 kg'}
2,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics,{'Height': '185.0 cm','Weight': '90.0 kg'}
3,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics,{'Height': '203.0 cm','Weight': '441.0 kg'}
4,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics,{'Height': '193.0 cm','Weight': '122.0 kg'}

In [246]:
# dropping the Measurements column.
df_info = df_info.drop(columns=['Measurements'])
df_info.head(3)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height(cm),Weight(kg)
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,{'Height': '203.0 cm','Weight': '441.0 kg'}
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,{'Height': '191.0 cm','Weight': '65.0 kg'}
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,{'Height': '185.0 cm','Weight': '90.0 kg'}

In [247]:
# Make a list of all characters to replace
to_replace = ['{','}', "'Height': ", "'", ' cm']
# run a loop to replace all of the characters in the list at once
for char in to_replace:
    df_info['Height(cm)'] = df_info['Height(cm)'].str.replace(char,'',regex=False)

# Remove 'Height: ' from the beginning of the values
df_info['Height(cm)'] = df_info['Height(cm)'].str.replace('Height: ', '', regex=False)

df_info['Height(cm)'].head()

0    203.0
1    191.0
2    185.0
3    203.0
4    193.0
Name: Height(cm), dtype: object

In [248]:
# Make a list of all characters to replace
to_replace = ['{', '}', "'Weight': ", "'", ' kg']
# run a loop to replace all of the characters in the list at once
for char in to_replace:
    df_info['Weight(kg)'] = df_info['Weight(kg)'].str.replace(char,'',regex=False)

# Remove 'Weight: ' from the beginning of the values
df_info['Weight(kg)'] = df_info['Weight(kg)'].str.replace('Weight: ', '', regex=False)

df_info['Weight(kg)'].head()

0     441.0
1      65.0
2      90.0
3     441.0
4     122.0
Name: Weight(kg), dtype: object

In [249]:
df_info['Height(cm)'] = df_info['Height(cm)'].str.replace("'",'')
df_info.head(3)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height(cm),Weight(kg)
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0,90.0

In [250]:
df_info['Weight(kg)'] = df_info['Weight(kg)'].str.replace("'",'')
df_info['Weight(kg)'].head()

0     441.0
1      65.0
2      90.0
3     441.0
4     122.0
Name: Weight(kg), dtype: object

In [251]:
# convert weight and height to float(decimal)
df_info['Height(cm)'] = df_info['Height(cm)'].astype(float)
df_info['Weight(kg)'] = df_info['Weight(kg)'].astype(float)
print(df_info.dtypes)

Gender         object
Race           object
Alignment      object
Hair color     object
Eye color      object
Skin color     object
Hero           object
Publisher      object
Height(cm)    float64
Weight(kg)    float64
dtype: object

In [259]:
# Reorder the columns as per your request
df_cleaned_info = df_info[["Hero", "Publisher", "Gender", "Eye color", "Race", "Hair color", "Height(cm)", "Skin color", "Alignment", "Weight(kg)"]]
df_cleaned_info

,Hero,Publisher,Gender,Eye color,Race,Hair color,Height(cm),Skin color,Alignment,Weight(kg)
0,A-Bomb,Marvel Comics,Male,yellow,Human,No Hair,203.0,Unknown,good,441.0
1,Abe Sapien,Dark Horse Comics,Male,blue,Icthyo Sapien,No Hair,191.0,blue,good,65.0
2,Abin Sur,DC Comics,Male,blue,Ungaran,No Hair,185.0,red,good,90.0
3,Abomination,Marvel Comics,Male,green,Human / Radiation,No Hair,203.0,Unknown,bad,441.0
4,Absorbing Man,Marvel Comics,Male,blue,Human,No Hair,193.0,Unknown,bad,122.0
...,...,...,...,...,...,...,...,...,...,...
458,Yellowjacket,Marvel Comics,Male,blue,Human,Blond,183.0,Unknown,good,83.0
459,Yellowjacket II,Marvel Comics,Female,blue,Human,Strawberry Blond,165.0,Unknown,good,52.0
460,Yoda,George Lucas,Male,brown,Yoda's species,White,66.0,green,good,17.0
461,Zatanna,DC Comics,Female,blue,Human,Black,170.0,Unknown,good,57.0
462,Zoom,DC Comics,Male,red,Unknown,Brown,185.0,Unknown,bad,81.0

In [253]:
# powers dataframe

In [254]:
df_powers.head(5)

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [255]:
df_powers['Powers'].value_counts()

Intelligence                                                                                                                                                                                                                                                         8
Durability,Super Strength                                                                                                                                                                                                                                            5
Agility,Stealth,Marksmanship,Weapons Master,Stamina                                                                                                                                                                                                                  4
Marksmanship                                                                                                                                                                                                                                                         4
Teleportation                                                                                                                                                                                                                                                        4
                                                                                                                                                                                                                                                                    ..
Accelerated Healing,Flight,Telepathy,Energy Blasts,Teleportation,Telekinesis,Astral Projection,Psionic Powers,Mind Blast,Regeneration,Illusions,Resurrection                                                                                                         1
Flight,Telepathy,Animal Oriented Powers,Gliding                                                                                                                                                                                                                      1
Accelerated Healing,Durability,Energy Absorption,Flight,Super Strength,Telepathy,Energy Blasts,Size Changing,Super Speed,Darkforce Manipulation,Enhanced Senses,Phasing,Invulnerability,Self-Sustenance,Gravity Control,Energy Manipulation,Time Travel,Illusions    1
Agility,Accelerated Healing,Super Strength,Super Speed,Animal Oriented Powers,Enhanced Senses,Jump,Reflexes,Natural Weapons                                                                                                                                          1
Super Speed,Intangibility,Time Travel,Time Manipulation                                                                                                                                                                                                              1
Name: Powers, Length: 608, dtype: int64

In [256]:
df_powers.dtypes

hero_names    object
Powers        object
dtype: object

In [261]:
# Ensure the 'Powers' column is a string type
df_powers['Powers'] = df_powers['Powers'].astype(str)

# Split the 'Powers' column into separate columns
powers_split = df_powers['Powers'].str.split(',', expand=True)

# Create one-hot-encoded columns for each unique power
unique_powers = powers_split.stack().str.get_dummies().max(level=0)

# Concatenate the one-hot-encoded columns with the original DataFrame
df_powers = pd.concat([df_powers, unique_powers], axis=1)

# Drop the original 'Powers' column
df_powers.drop('Powers', axis=1, inplace=True)

KeyError: 'Powers'

In [258]:
df_powers.head()

,hero_names,Accelerated Healing,Adaptation,Agility,Animal Attributes,Animal Control,Animal Oriented Powers,Animation,Anti-Gravity,Astral Projection,...,Vision - Thermal,Vision - X-Ray,Vitakinesis,Wallcrawling,Water Control,Weapon-based Powers,Weapons Master,Weather Control,Web Creation,Wind Control
0,3-D Man,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,A-Bomb,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Abe Sapien,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,Abin Sur,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Abomination,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [260]:
#merging the two files
df_clean_data = df_cleaned_info.merge(df_powers, how='cross')
df_clean_data

,Hero,Publisher,Gender,Eye color,Race,Hair color,Height(cm),Skin color,Alignment,Weight(kg),...,Vision - Thermal,Vision - X-Ray,Vitakinesis,Wallcrawling,Water Control,Weapon-based Powers,Weapons Master,Weather Control,Web Creation,Wind Control
0,A-Bomb,Marvel Comics,Male,yellow,Human,No Hair,203.0,Unknown,good,441.0,...,0,0,0,0,0,0,0,0,0,0
1,A-Bomb,Marvel Comics,Male,yellow,Human,No Hair,203.0,Unknown,good,441.0,...,0,0,0,0,0,0,0,0,0,0
2,A-Bomb,Marvel Comics,Male,yellow,Human,No Hair,203.0,Unknown,good,441.0,...,0,0,0,0,0,0,1,0,0,0
3,A-Bomb,Marvel Comics,Male,yellow,Human,No Hair,203.0,Unknown,good,441.0,...,0,0,0,0,0,0,0,0,0,0
4,A-Bomb,Marvel Comics,Male,yellow,Human,No Hair,203.0,Unknown,good,441.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308816,Zoom,DC Comics,Male,red,Unknown,Brown,185.0,Unknown,bad,81.0,...,0,0,0,0,0,0,0,0,0,0
308817,Zoom,DC Comics,Male,red,Unknown,Brown,185.0,Unknown,bad,81.0,...,0,0,0,0,0,0,0,0,0,0
308818,Zoom,DC Comics,Male,red,Unknown,Brown,185.0,Unknown,bad,81.0,...,0,0,0,0,0,0,1,0,0,0
308819,Zoom,DC Comics,Male,red,Unknown,Brown,185.0,Unknown,bad,81.0,...,0,0,0,0,1,0,0,1,0,0
308820,Zoom,DC Comics,Male,red,Unknown,Brown,185.0,Unknown,bad,81.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# new dataframe

In [267]:
# Calculate the average weight of characters with Super Speed
average_weight = df_clean_data[df_clean_data['Super Speed'] == 1]['Weight(kg)'].mean()

# Calculate the average weight of characters without Super Speed
average_weight = df_clean_data[df_clean_data['Super Speed'] == 0]['Weight(kg)'].mean()

print("Average weight of characters with Super Speed:", average_weight)
print("Average weight of characters without Super Speed:", average_weight)

Average weight of characters with Super Speed: 113.58963282937366
Average weight of characters without Super Speed: 113.58963282937366

In [269]:
# Group the DataFrame by 'Publisher' and calculate the average height for each group
average_height = df_clean_data.groupby('Publisher')['Height(cm)'].mean()

# Display the result
print(average_height)

Publisher
DC Comics            181.923913
Dark Horse Comics    176.909091
George Lucas         159.600000
Image Comics         211.000000
Marvel Comics        191.546128
Shueisha             171.500000
Star Trek            181.500000
Team Epic TV         180.750000
Unknown              178.000000
Name: Height(cm), dtype: float64